table FAITVENTES
	lineageTag: 6057ea8f-8ab8-49f2-bd72-72d269e03eed

	column ID_COMMANDE
		dataType: int64
		lineageTag: c6c3a4ec-5fe8-4bc0-b294-39c5d13415eb
		summarizeBy: none
		sourceColumn: ID_COMMANDE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID_CLIENT
		dataType: int64
		lineageTag: cbf1ed6e-aef4-4540-b3eb-1fc91c303c9e
		summarizeBy: none
		sourceColumn: ID_CLIENT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"FAITVENTES","TableItemName":"ID_CLIENT (clusters)","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"FAITVENTES","TableItemName":"ID_CLIENT (clusters) 2","ObjectType":4},"LinkType":"UsedInGroup"}]

	column ID_PT_VENTE
		dataType: int64
		lineageTag: c6eb6597-88b3-40b4-b2bf-d8513ac099c4
		summarizeBy: none
		sourceColumn: ID_PT_VENTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID_PRODUIT
		dataType: int64
		lineageTag: db400247-f5c7-47d7-a553-8813ed4a8643
		summarizeBy: none
		sourceColumn: ID_PRODUIT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID_RETOURS
		dataType: int64
		lineageTag: 20568919-f285-4b1d-8122-3377462fa9de
		summarizeBy: none
		sourceColumn: ID_RETOURS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID_FACTURE
		dataType: int64
		lineageTag: 791f53bb-2631-4c0d-9cbe-7332ea899429
		summarizeBy: none
		sourceColumn: ID_FACTURE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MT_VENTE
		dataType: double
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 525cc3e7-4444-45bc-a1a1-e375e442d752
		summarizeBy: sum
		sourceColumn: MT_VENTE

		annotation SummarizationSetBy = Automatic

	column MT_QUANTITE
		dataType: double
		lineageTag: 9930008a-4000-49a2-8dca-22e08dcd9fc3
		summarizeBy: sum
		sourceColumn: MT_QUANTITE

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"FAITVENTES","TableItemName":"MT_QUANTITE (compartiments)","ObjectType":4},"LinkType":"UsedInGroup"}]

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MT_PROFIT
		dataType: double
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 024974b3-ed3f-47d5-a4b9-0d82a81b8309
		summarizeBy: sum
		sourceColumn: MT_PROFIT

		annotation SummarizationSetBy = Automatic

	column MT_REMISE
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 035329b6-ad52-41d5-bd0e-1e990c8f898e
		summarizeBy: average
		sourceColumn: MT_REMISE

		annotation SummarizationSetBy = User

	column DT_COMMANDE
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 13df1319-67c4-4d8a-9224-4607c555948f
		summarizeBy: none
		sourceColumn: DT_COMMANDE

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column DT_EXPEDITION
		dataType: dateTime
		formatString: Short Date
		lineageTag: e1dae8fb-1b6c-45b6-a684-1594f9e4646c
		summarizeBy: none
		sourceColumn: DT_EXPEDITION

		variation Variation
			isDefault
			relationship: 9445ca25-92e3-46ae-b4cb-5918c925753c
			defaultHierarchy: LocalDateTable_39a62f7b-decc-4f74-9e49-3411a37b9cb1.'Hiérarchie de dates'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'DIMFACTURE.NUM_FACTURE'
		dataType: string
		lineageTag: c209196a-df51-4e3f-b8c1-7a2756d99ca8
		summarizeBy: none
		sourceColumn: DIMFACTURE.NUM_FACTURE

		annotation SummarizationSetBy = Automatic

	column 'identification commande non facturée'
		dataType: int64
		formatString: 0
		lineageTag: 75777781-8f18-453f-ba9e-9613f027e4d9
		summarizeBy: sum
		sourceColumn: identification commande non facturée

		annotation SummarizationSetBy = Automatic

	column 'MT_QUANTITE (compartiments)' = ```
			VAR __Count = 7
			
			VAR __Min = MIN('FAITVENTES'[MT_QUANTITE])
			
			VAR __Max = MAX('FAITVENTES'[MT_QUANTITE])
			
			VAR __Difference = (__Max - __Min)
			
			VAR __Size = IF(__Difference > 0, __Difference / __Count, 1)
			
			VAR __BinNumber = 
				IF(
					ISBLANK('FAITVENTES'[MT_QUANTITE]),
					BLANK(),
					ROUNDDOWN(('FAITVENTES'[MT_QUANTITE] - __Min) / __Size, 0)
				)
			
			RETURN
				IF(
					ISBLANK('FAITVENTES'[MT_QUANTITE]),
					BLANK(),
					__Min + (MIN(__BinNumber, __Count - 1) * __Size)
				)
			```
		lineageTag: 589cfa81-cdeb-4709-88ac-c6022af0e078
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "FAITVENTES"
				          }
				        },
				        "Property": "MT_QUANTITE"
				      }
				    }
				  ],
				  "version": 0
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"f","Entity":"FAITVENTES"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"MT_QUANTITE"}}],"BinItem":{"Expression":{"Member":{"Expression":{"Discretize":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"MT_QUANTITE"}},"Count":7}},"Member":"Min"}}}}

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Clusters pour ID_CLIENT
	column 'ID_CLIENT (clusters)' = ```
			VAR __ClusterValue = 
				LOOKUPVALUE(
					'ClusterMappingTable'[ClusterId],
					'ClusterMappingTable'[ID_CLIENT],
					'FAITVENTES'[ID_CLIENT]
				)
			
			RETURN
				SWITCH(
					__ClusterValue,
					BLANK(),
					BLANK(),
					CONCATENATE("Cluster", __ClusterValue)
				)
			```
		lineageTag: 97f2cd27-336c-4599-bf80-163a1ff733f2
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "FAITVENTES"
				          }
				        },
				        "Property": "ID_CLIENT"
				      }
				    }
				  ],
				  "version": 0
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"f","Entity":"FAITVENTES"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"ID_CLIENT"}}],"PartitionTable":{"Definition":{"TableDefinition":{"Version":2,"From":[{"Name":"t","Entity":"Tables Mesures"},{"Name":"f","Entity":"FAITVENTES"}],"Where":[],"OrderBy":[],"Select":[{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"FAITVENTES.ID_CLIENT"},"Name":"FAITVENTES.ID_CLIENT"},{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"clusterId"},"Name":"clusterId"}],"GroupBy":[],"Transform":[{"Name":"KMeansClustering","Algorithm":"KMeansClustering","Input":{"Parameters":[{"Literal":{"Value":"-1L"},"Name":"NumberOfClusters"}],"Table":{"Name":"input0","Columns":[{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Total Ventes"},"Name":"Tables Mesures.Total Ventes"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Total Profit"},"Name":"Tables Mesures.Total Profit"}},{"Role":"Item","Expression":{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"ID_CLIENT"},"Name":"FAITVENTES.ID_CLIENT"}}]}},"Output":{"Table":{"Name":"output0","Columns":[{"Expression":{"Column":{"Expression":{"TransformTableRef":{"Source":"input0"}},"Property":"FAITVENTES.ID_CLIENT"},"Name":"FAITVENTES.ID_CLIENT"}},{"Role":"Series","Expression":{"TransformOutputRoleRef":{"Role":"ClusterId"},"Name":"clusterId"}}]}}}]},"ItemIdColumns":["FAITVENTES.ID_CLIENT"],"PartitionIdColumn":"clusterId","Partitions":[{"PartitionIds":[{"Literal":{"Value":"null"}}]}],"DefaultPartitionPrefix":"Cluster"},"Result":{"TableName":"ClusterMappingTable","PartitionIdColumn":"ClusterId","ItemIdMappings":[[{"PartitionTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"ClusterMappingTable"}},"Property":"ID_CLIENT"}},"SourceTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"FAITVENTES"}},"Property":"ID_CLIENT"}}}]]}}}

		annotation SummarizationSetBy = Automatic

	/// Clusters pour ID_CLIENT
	column 'ID_CLIENT (clusters) 2' = ```
			VAR __ClusterValue = 
				LOOKUPVALUE(
					'ClusterMappingTable 2'[ClusterId],
					'ClusterMappingTable 2'[ID_CLIENT],
					'FAITVENTES'[ID_CLIENT]
				)
			
			RETURN
				SWITCH(
					__ClusterValue,
					BLANK(),
					BLANK(),
					CONCATENATE("Cluster", __ClusterValue)
				)
			```
		lineageTag: b064f87b-3e66-4eee-a3a3-0df2ce24960a
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "FAITVENTES"
				          }
				        },
				        "Property": "ID_CLIENT"
				      }
				    }
				  ],
				  "version": 0
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"f","Entity":"FAITVENTES"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"ID_CLIENT"}}],"PartitionTable":{"Definition":{"TableDefinition":{"Version":2,"From":[{"Name":"t","Entity":"Tables Mesures"},{"Name":"f","Entity":"FAITVENTES"},{"Name":"p","Entity":"Paramètre"}],"Where":[{"Condition":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"Paramètre Champs"}}],"Values":[[{"Literal":{"Value":"'''Tables Mesures''[Total Ventes]'"}}]]}}}],"OrderBy":[],"Select":[{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"FAITVENTES.ID_CLIENT"},"Name":"FAITVENTES.ID_CLIENT"},{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"clusterId"},"Name":"clusterId"}],"GroupBy":[],"Transform":[{"Name":"KMeansClustering","Algorithm":"KMeansClustering","Input":{"Parameters":[{"Literal":{"Value":"7L"},"Name":"NumberOfClusters"}],"Table":{"Name":"input0","Columns":[{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Total Ventes"},"Name":"Tables Mesures.Total Ventes"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Total Profit"},"Name":"Tables Mesures.Total Profit"}},{"Role":"Item","Expression":{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"ID_CLIENT"},"Name":"FAITVENTES.ID_CLIENT"}}]}},"Output":{"Table":{"Name":"output0","Columns":[{"Expression":{"Column":{"Expression":{"TransformTableRef":{"Source":"input0"}},"Property":"FAITVENTES.ID_CLIENT"},"Name":"FAITVENTES.ID_CLIENT"}},{"Role":"Series","Expression":{"TransformOutputRoleRef":{"Role":"ClusterId"},"Name":"clusterId"}}]}}}]},"ItemIdColumns":["FAITVENTES.ID_CLIENT"],"PartitionIdColumn":"clusterId","Partitions":[{"PartitionIds":[{"Literal":{"Value":"null"}}]}],"DefaultPartitionPrefix":"Cluster"},"Result":{"TableName":"ClusterMappingTable 2","PartitionIdColumn":"ClusterId","ItemIdMappings":[[{"PartitionTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"ClusterMappingTable 2"}},"Property":"ID_CLIENT"}},"SourceTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"FAITVENTES"}},"Property":"ID_CLIENT"}}}]]}}}

		annotation SummarizationSetBy = Automatic

	partition FAITVENTES-824edb2b-f9db-4c2f-a76f-46b403966215 = m
		mode: import
		source =
				let
				    Source = Sql.Database(AzureServeur, AzureBDD),
				    M203_Schema = Source{[Name="M203",Kind="Schema"]}[Data],
				    FAITVENTES_Table = Source{[Schema="dbo",Item="FAITVENTES"]}[Data],
				    #"Requêtes fusionnées" = Table.NestedJoin(FAITVENTES_Table, {"ID_FACTURE"}, DIMFACTURE, {"ID_FACTURE"}, "DIMFACTURE", JoinKind.LeftOuter),
				    #"DIMFACTURE développé" = Table.ExpandTableColumn(#"Requêtes fusionnées", "DIMFACTURE", {"NUM_FACTURE"}, {"DIMFACTURE.NUM_FACTURE"}),
				    #"identification commande non facturée" = Table.AddColumn(#"DIMFACTURE développé", "Personnalisé", each if [DIMFACTURE.NUM_FACTURE] = null then 1 else 0),
				    #"Type modifié" = Table.TransformColumnTypes(#"identification commande non facturée",{{"Personnalisé", Int64.Type}}),
				    #"Colonnes renommées" = Table.RenameColumns(#"Type modifié",{{"Personnalisé", "identification commande non facturée"}}),
				    #"Type modifié1" = Table.TransformColumnTypes(#"Colonnes renommées",{{"DT_COMMANDE", type datetime}})
				in
				    #"Type modifié1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

