{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DIMCOMMANDE\",\"DIMCLIENTS\",\"DIMFACTURE\",\"DIMPOINTDEVENTE\",\"DIMPRODUIT\",\"DIMRETOURS\",\"FAITVENTES\",\"generation_calendrier\",\"Calendrier\",\"Table jours fériés\",\"Table 1\",\"Année\",\"fonction_generation_jour_ferie_par_annne\",\"Source_BDD\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.1203.0 (24.07)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "fr-FR",
    "cultures": [
      {
        "name": "fr-FR",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "fastCombine": true,
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "generation_calendrier",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "CreateDateTable = (StartDate as date, EndDate as date, optional Culture as nullable text) as table =>",
          "let",
          "DayCount = Duration.Days(Duration.From(EndDate - StartDate)),",
          "Source = List.Dates(StartDate,DayCount,#duration(1,0,0,0)),",
          "TableFromList = Table.FromList(Source, Splitter.SplitByNothing()),",
          "ChangedType = Table.TransformColumnTypes(TableFromList,{{\"Column1\", type date}}),",
          "RenamedColumns = Table.RenameColumns(ChangedType,{{\"Column1\", \"Date\"}}),",
          "InsertYear = Table.AddColumn(RenamedColumns, \"Année\", each Date.Year([Date]), Int64.Type),",
          "InsertQuarter = Table.AddColumn(InsertYear, \"Trimestre\", each Date.QuarterOfYear([Date]), Int64.Type),",
          "InsertMonth = Table.AddColumn(InsertQuarter, \"MoisNombre\", each Date.Month([Date]), Int64.Type),",
          "InsertDay = Table.AddColumn(InsertMonth, \"Jour\", each Date.Day([Date]), Int64.Type),",
          "InsertDayInt = Table.AddColumn(InsertDay, \"DateNombre\", each [Année] * 10000 + [MoisNombre] * 100 + [Jour]),",
          "InsertMonthName = Table.AddColumn(InsertDayInt, \"MoisNom\", each Date.ToText([Date], \"MMMM\", Culture), type text),",
          "InsertCalendarMonth = Table.AddColumn(InsertMonthName, \"MoisCalendrier\", each (try(Text.Range([MoisNom],0,3))",
          "otherwise [MoisNom]) & \" \" & Number.ToText([Année])),",
          "InsertCalendarQtr = Table.AddColumn(InsertCalendarMonth, \"TrimestreCalendrier\", each \"T\" & Number.ToText([Trimestre]) &",
          "\" \" & Number.ToText([Année])),",
          "InsertDayWeek = Table.AddColumn(InsertCalendarQtr, \"JourSemaine\", each Date.DayOfWeek([Date])),",
          "InsertDayName = Table.AddColumn(InsertDayWeek, \"NomJourSemaine\", each Date.ToText([Date], \"dddd\", Culture), type",
          "text),",
          "InsertWeekEnding = Table.AddColumn(InsertDayName, \"FinSemaine\", each Date.EndOfWeek([Date]), type date)",
          "in",
          "InsertWeekEnding",
          "in",
          "CreateDateTable"
        ],
        "kind": "m",
        "lineageTag": "96801e38-d7ee-44b7-9c19-85fd8e10b8d3"
      },
      {
        "name": "Année",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"2013\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "fedbeeba-8af3-4cc5-82a7-e73935dd5a67",
        "queryGroup": "fonction_generation_jour_ferie_par_annne"
      },
      {
        "name": "fonction_generation_jour_ferie_par_annne",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Année as text) => let",
          "    Source = Web.BrowserContents(\"https://kalendrier.ouest-france.fr/jours-feries/\" & Année & \".html\"),",
          "    #\"Table extraite à partir de code Html\" = Html.Table(Source, {{\"Column1\", \"TD:nth-child(1)\"}, {\"Column2\", \".url\"}, {\"Column3\", \"TD + *\"}, {\"Column4\", \".location\"}}, [RowSelector=\".vevent\"]),",
          "    #\"Type modifié\" = Table.TransformColumnTypes(#\"Table extraite à partir de code Html\",{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}}),",
          "    #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Type modifié\",{\"Column4\"}),",
          "    #\"Colonnes renommées\" = Table.RenameColumns(#\"Colonnes supprimées\",{{\"Column1\", \"LIBELLE JOUR\"}, {\"Column2\", \"LIBELLE 2 JOURS\"}, {\"Column3\", \"DATE TEXTE\"}})",
          "in",
          "    #\"Colonnes renommées\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "b382b857-d4de-45a2-9df4-427799bf0bdb",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Table 1\"\"}\" ]",
        "queryGroup": "fonction_generation_jour_ferie_par_annne"
      },
      {
        "name": "Source_BDD",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"dsn=DWH_Manuel\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "fdcecec0-b488-4f3e-bdf9-9a79255bf46d"
      },
      {
        "name": "Table jours fériés",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = generation_calendrier(#date(2011, 1, 1), #date(2020, 12, 31), null),",
          "    #\"Autres colonnes supprimées\" = Table.SelectColumns(Source,{\"Année\"}),",
          "    #\"Doublons supprimés\" = Table.Distinct(#\"Autres colonnes supprimées\"),",
          "    #\"Type modifié\" = Table.TransformColumnTypes(#\"Doublons supprimés\",{{\"Année\", type text}}),",
          "    #\"Fonction personnalisée appelée\" = Table.AddColumn(#\"Type modifié\", \"appel jours fériés\", each fonction_generation_jour_ferie_par_annne([Année])),",
          "    #\"appel jours fériés développé\" = Table.ExpandTableColumn(#\"Fonction personnalisée appelée\", \"appel jours fériés\", {\"LIBELLE JOUR\", \"LIBELLE 2 JOURS\", \"DATE TEXTE\"}, {\"appel jours fériés.LIBELLE JOUR\", \"appel jours fériés.LIBELLE 2 JOURS\", \"appel jours fériés.DATE TEXTE\"}),",
          "    #\"Duplication de la colonne\" = Table.DuplicateColumn(#\"appel jours fériés développé\", \"appel jours fériés.DATE TEXTE\", \"appel jours fériés.DATE TEXTE - Copier\"),",
          "    #\"Valeur remplacée\" = Table.ReplaceValue(#\"Duplication de la colonne\",\"1er\",\"1\",Replacer.ReplaceText,{\"appel jours fériés.DATE TEXTE - Copier\"}),",
          "    #\"Type modifié1\" = Table.TransformColumnTypes(#\"Valeur remplacée\",{{\"appel jours fériés.DATE TEXTE - Copier\", type date}}),",
          "    #\"Colonnes renommées\" = Table.RenameColumns(#\"Type modifié1\",{{\"appel jours fériés.DATE TEXTE - Copier\", \"Date jour férié\"}})",
          "in",
          "    #\"Colonnes renommées\""
        ],
        "kind": "m",
        "lineageTag": "18e45133-1644-4d8b-824f-38235b6eaf09"
      },
      {
        "name": "Table 1",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.BrowserContents(\"https://kalendrier.ouest-france.fr/jours-feries/\" & Année & \".html\"),",
          "    #\"Table extraite à partir de code Html\" = Html.Table(Source, {{\"Column1\", \"TD:nth-child(1)\"}, {\"Column2\", \".url\"}, {\"Column3\", \"TD + *\"}, {\"Column4\", \".location\"}}, [RowSelector=\".vevent\"]),",
          "    #\"Type modifié\" = Table.TransformColumnTypes(#\"Table extraite à partir de code Html\",{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}}),",
          "    #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Type modifié\",{\"Column4\"}),",
          "    #\"Colonnes renommées\" = Table.RenameColumns(#\"Colonnes supprimées\",{{\"Column1\", \"LIBELLE JOUR\"}, {\"Column2\", \"LIBELLE 2 JOURS\"}, {\"Column3\", \"DATE TEXTE\"}})",
          "in",
          "    #\"Colonnes renommées\""
        ],
        "kind": "m",
        "lineageTag": "1cbb9cdc-f494-4685-94a8-94ba6bf66a77",
        "queryGroup": "fonction_generation_jour_ferie_par_annne"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "fonction_generation_jour_ferie_par_annne"
      }
    ],
    "relationships": [
      {
        "name": "9d5049e4-7c09-40b4-ba10-f8f8c1f5510d",
        "fromColumn": "DATE_COMMANDE",
        "fromTable": "DIMCOMMANDE",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_20d9266d-585c-4b9f-8819-5ab9709adce8"
      },
      {
        "name": "42e1c31c-9618-4782-81f6-316e4639e642",
        "fromColumn": "DATE_EXPEDITION",
        "fromTable": "DIMCOMMANDE",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_60b4f678-d96c-423b-98bc-d62093ff4f97"
      },
      {
        "name": "2dd5143c-997f-43c5-b14c-a3dc35cd19a2",
        "fromColumn": "DATE_FACTURE",
        "fromTable": "DIMFACTURE",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c3c9ee78-a960-40be-96ba-5bcbb968c87e"
      },
      {
        "name": "015e45e7-9a44-47ec-95c6-567e635fb471",
        "fromColumn": "ID_COMMANDE",
        "fromTable": "FAITVENTES",
        "toColumn": "ID_COMMANDE",
        "toTable": "DIMCOMMANDE"
      },
      {
        "name": "a136ae38-844b-4f4f-99ab-9355fe79533d",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "NUM_COMMANDE",
        "fromTable": "DIMRETOURS",
        "toColumn": "NUM_COMMANDE",
        "toTable": "DIMCOMMANDE"
      },
      {
        "name": "f65246ab-e7af-44bc-82ae-021ac92ed9d5",
        "fromColumn": "ID_CLIENT",
        "fromTable": "FAITVENTES",
        "toColumn": "ID_CLIENT",
        "toTable": "DIMCLIENTS"
      },
      {
        "name": "b3bf4891-1f23-497f-9fe2-66a572eb4b11",
        "fromColumn": "ID_FACTURE",
        "fromTable": "FAITVENTES",
        "toColumn": "ID_FACTURE",
        "toTable": "DIMFACTURE"
      },
      {
        "name": "4065a3c1-eabf-4e61-86db-af79f82557de",
        "fromColumn": "ID_PRODUIT",
        "fromTable": "FAITVENTES",
        "toColumn": "ID_PRODUIT",
        "toTable": "DIMPRODUIT"
      },
      {
        "name": "5fb79e16-d2d6-4c00-8f7b-764d982a0039",
        "fromColumn": "ID_RETOURS",
        "fromTable": "FAITVENTES",
        "isActive": false,
        "toColumn": "ID_RETOURS",
        "toTable": "DIMRETOURS"
      },
      {
        "name": "bc1c7e84-bd9d-44d5-887f-b01b60760262",
        "fromColumn": "ID_PT_VENTE",
        "fromTable": "FAITVENTES",
        "toColumn": "ID_PT_VENTE",
        "toTable": "DIMPOINTDEVENTE"
      },
      {
        "name": "ffa41a71-bd53-403b-a2f8-471e7c8f2277",
        "fromColumn": "DT_COMMANDE",
        "fromTable": "FAITVENTES",
        "toColumn": "Date",
        "toTable": "Calendrier"
      },
      {
        "name": "e7dc363b-d231-4cf3-9307-f5824d6d0527",
        "fromColumn": "DT_EXPEDITION",
        "fromTable": "FAITVENTES",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendrier"
      }
    ],
    "sourceQueryCulture": "fr-FR",
    "tables": [
      {
        "name": "DIMCOMMANDE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_COMMANDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9b01f0b8-468f-45e8-b004-21b17043215a",
            "sourceColumn": "ID_COMMANDE",
            "summarizeBy": "none"
          },
          {
            "name": "NUM_COMMANDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f48abb54-6a76-4146-b6a8-59141b7c084d",
            "sourceColumn": "NUM_COMMANDE",
            "summarizeBy": "none"
          },
          {
            "name": "DATE_COMMANDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3f1fb97b-10b8-4343-95cd-c631d8a80b93",
            "sourceColumn": "DATE_COMMANDE",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hiérarchie de dates",
                  "table": "LocalDateTable_20d9266d-585c-4b9f-8819-5ab9709adce8"
                },
                "isDefault": true,
                "relationship": "9d5049e4-7c09-40b4-ba10-f8f8c1f5510d"
              }
            ]
          },
          {
            "name": "DATE_EXPEDITION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "41f8c865-3cc8-4ff2-9cdd-3818e1e3b7a6",
            "sourceColumn": "DATE_EXPEDITION",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hiérarchie de dates",
                  "table": "LocalDateTable_60b4f678-d96c-423b-98bc-d62093ff4f97"
                },
                "isDefault": true,
                "relationship": "42e1c31c-9618-4782-81f6-316e4639e642"
              }
            ]
          },
          {
            "name": "LB_MODE_EXPEDITION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "666c32d3-2119-4e12-b640-2c518c61a6b9",
            "sourceColumn": "LB_MODE_EXPEDITION",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "136eb7c8-12d4-420c-96a3-f9c288a72cda",
        "partitions": [
          {
            "name": "DIMCOMMANDE-47d92f64-d4bf-4d60-befb-b11b1ed8ccf4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Odbc.DataSource(Source_BDD, [HierarchicalNavigation=true]),",
                "    M203_Schema = Source{[Name=\"M203\",Kind=\"Schema\"]}[Data],",
                "    DIMCOMMANDE_Table = M203_Schema{[Name=\"DIMCOMMANDE\",Kind=\"Table\"]}[Data]",
                "in",
                "    DIMCOMMANDE_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_f15e7891-ac24-402b-b6f8-c42f96260197",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b4f04281-0ea9-4728-96dc-c5d6f5d97413",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Année",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "abcc5518-46f7-43bc-833b-275ac7794927",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoMois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d1cbcc8b-c71b-4463-9949-c6abdbee9ed5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ce60b6aa-f2bc-47b6-a0d9-ce79d2c34f2f",
            "sortByColumn": "NoMois",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NoMois] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4aa3045a-4c04-4f06-9601-0f25ff46c1f9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [NoTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c35e313e-42f3-415d-ac19-44532422f5f1",
            "sortByColumn": "NoTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Jour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bf2d39c1-891b-42e0-8b30-bf5aab41beb2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Année",
                "column": "Année",
                "lineageTag": "158d8046-24cb-47d8-8f91-e664a414eda6",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "85135a34-c566-4214-9cd5-8c762c2ce174",
                "ordinal": 1
              },
              {
                "name": "Mois",
                "column": "Mois",
                "lineageTag": "1e7842ef-cf58-493f-900f-b904cfe38c0c",
                "ordinal": 2
              },
              {
                "name": "Jour",
                "column": "Jour",
                "lineageTag": "a82991b4-45de-427a-80cc-81b0debde480",
                "ordinal": 3
              }
            ],
            "lineageTag": "87881b61-5268-43bb-940d-de0f128df329"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "64beacc1-418f-49ba-95c6-b93cb1e8c38d",
        "partitions": [
          {
            "name": "DateTableTemplate_f15e7891-ac24-402b-b6f8-c42f96260197-3f60d348-84a1-4724-91e2-41b8a79da1bf",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_20d9266d-585c-4b9f-8819-5ab9709adce8",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f81ee883-83cc-413d-b908-3276ca7c907c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Année",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cf9f9ddf-89ef-423b-948d-053622f9b28c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoMois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6002453a-9fc6-4e81-9a15-36fd36e5ed3c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "531fcc52-357e-4262-bdcc-1cd10e925445",
            "sortByColumn": "NoMois",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NoMois] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "eca91d77-d519-4375-b5f9-80e24d7bb956",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [NoTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "37657be8-6a77-4a80-9610-58401086f849",
            "sortByColumn": "NoTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Jour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8f7cca9e-fbe8-4ae8-a8da-9a1f08a9b4fe",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Année",
                "column": "Année",
                "lineageTag": "434c8e23-c342-4e3d-b616-2c4072c46c56",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "80d83af1-90b1-4375-997d-9fbccbfa6d9a",
                "ordinal": 1
              },
              {
                "name": "Mois",
                "column": "Mois",
                "lineageTag": "0450fb7f-354b-4588-aca9-d958c3fd9ab1",
                "ordinal": 2
              },
              {
                "name": "Jour",
                "column": "Jour",
                "lineageTag": "91095224-3c11-40cf-afe7-f60b8a174072",
                "ordinal": 3
              }
            ],
            "lineageTag": "1dc448d8-b4dd-405e-8c59-8dd58802e708"
          }
        ],
        "isHidden": true,
        "lineageTag": "2eb8987c-5107-44df-8367-5f939966a4f6",
        "partitions": [
          {
            "name": "LocalDateTable_20d9266d-585c-4b9f-8819-5ab9709adce8-ad1a20e6-501b-4580-a769-2704b9fefc2e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DIMCOMMANDE'[DATE_COMMANDE])), 1, 1), Date(Year(MAX('DIMCOMMANDE'[DATE_COMMANDE])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_60b4f678-d96c-423b-98bc-d62093ff4f97",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3342f65b-94d7-4bee-827d-a24e11024715",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Année",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6e76ab19-6960-45dc-8eca-8ce1f0cccbe0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoMois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "53f30055-b9c2-452a-823c-3fff2c35c1a4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7bcaaa90-16ee-4883-af10-db16960d83f6",
            "sortByColumn": "NoMois",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NoMois] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8ed4fd22-2bf3-49e3-b711-9bf92b4e067b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [NoTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7282804e-1b42-4a31-ad3a-ce79b34628b9",
            "sortByColumn": "NoTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Jour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d195b7b5-cdc3-41cf-a366-517b5cee5541",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Année",
                "column": "Année",
                "lineageTag": "773ab02c-5a24-4057-8b90-e611eff2977b",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "9159d856-4a30-49a2-870a-45a7f275d541",
                "ordinal": 1
              },
              {
                "name": "Mois",
                "column": "Mois",
                "lineageTag": "4e506dd2-d43e-46dc-b038-0005cdffb5ba",
                "ordinal": 2
              },
              {
                "name": "Jour",
                "column": "Jour",
                "lineageTag": "5b0df576-f3ca-4405-b48c-7a7c854d2d86",
                "ordinal": 3
              }
            ],
            "lineageTag": "c50b9aeb-5c80-4fc3-981d-2731a0977f8c"
          }
        ],
        "isHidden": true,
        "lineageTag": "a5a524c1-ca11-459d-bd67-0d225b2751dd",
        "partitions": [
          {
            "name": "LocalDateTable_60b4f678-d96c-423b-98bc-d62093ff4f97-8d181ff4-16d8-4962-91a3-4d79b71db0a6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DIMCOMMANDE'[DATE_EXPEDITION])), 1, 1), Date(Year(MAX('DIMCOMMANDE'[DATE_EXPEDITION])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "DIMCLIENTS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_CLIENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "71cdd196-91f8-4451-8a09-485ea9308504",
            "sourceColumn": "ID_CLIENT",
            "summarizeBy": "none"
          },
          {
            "name": "CD_CLIENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db0e39c1-4342-4fdc-acd8-b1691a6216d0",
            "sourceColumn": "CD_CLIENT",
            "summarizeBy": "none"
          },
          {
            "name": "LB_NOM_CLIENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8aac194-5d22-434b-9a01-84e53494acf1",
            "sourceColumn": "LB_NOM_CLIENT",
            "summarizeBy": "none"
          },
          {
            "name": "LB_NOM_SEGMENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fbbc05b7-1372-44ff-88fd-8f063b713a9c",
            "sourceColumn": "LB_NOM_SEGMENT",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "791cb1b7-ab5d-4ce5-9af3-3b6e4f4c0b65",
        "partitions": [
          {
            "name": "DIMCLIENTS-e05d7cd7-feaa-4a66-b1db-6a75e8f82b38",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Odbc.DataSource(Source_BDD, [HierarchicalNavigation=true]),",
                "    M203_Schema = Source{[Name=\"M203\",Kind=\"Schema\"]}[Data],",
                "    DIMCLIENTS_Table = M203_Schema{[Name=\"DIMCLIENTS\",Kind=\"Table\"]}[Data]",
                "in",
                "    DIMCLIENTS_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIMFACTURE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_FACTURE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a8517591-24bb-49e7-a7f2-b89f67b7ffe8",
            "sourceColumn": "ID_FACTURE",
            "summarizeBy": "none"
          },
          {
            "name": "NUM_FACTURE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f6d2b46-c728-4298-a477-5009aba94282",
            "sourceColumn": "NUM_FACTURE",
            "summarizeBy": "none"
          },
          {
            "name": "DATE_FACTURE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "68175f5a-4c12-4426-a869-974f13bc5e07",
            "sourceColumn": "DATE_FACTURE",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hiérarchie de dates",
                  "table": "LocalDateTable_c3c9ee78-a960-40be-96ba-5bcbb968c87e"
                },
                "isDefault": true,
                "relationship": "2dd5143c-997f-43c5-b14c-a3dc35cd19a2"
              }
            ]
          }
        ],
        "lineageTag": "d2aa44be-295a-4601-a949-5ec26d59cd8d",
        "partitions": [
          {
            "name": "DIMFACTURE-72e55ad5-59bc-453e-8519-4c77e54de35f",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Odbc.DataSource(Source_BDD, [HierarchicalNavigation=true]),",
                "    M203_Schema = Source{[Name=\"M203\",Kind=\"Schema\"]}[Data],",
                "    DIMFACTURE_Table = M203_Schema{[Name=\"DIMFACTURE\",Kind=\"Table\"]}[Data]",
                "in",
                "    DIMFACTURE_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c3c9ee78-a960-40be-96ba-5bcbb968c87e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c4c482c9-1ec2-477a-bec5-f042adcc4bb9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Année",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2d186ce9-d745-4069-923f-58c06ce88a1e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoMois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ee1b3f03-6c2a-44b3-845e-5d301849ff9d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "234701fd-ce6b-4ced-a29c-3db9c7483622",
            "sortByColumn": "NoMois",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NoMois] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "35adc10e-9bc9-4c47-8dbc-c8bb24e17077",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [NoTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4b432931-4d96-488d-880b-4b3d4d166c6f",
            "sortByColumn": "NoTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Jour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "73434f3a-2458-4472-bbce-37c33808fc79",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Année",
                "column": "Année",
                "lineageTag": "307c000e-8df1-4ed3-97a0-3ce483bb2a03",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "0c7a6c6d-a303-4ed8-8992-2280e706f3d1",
                "ordinal": 1
              },
              {
                "name": "Mois",
                "column": "Mois",
                "lineageTag": "1b9aa127-41d9-4b74-9699-e79427e4e140",
                "ordinal": 2
              },
              {
                "name": "Jour",
                "column": "Jour",
                "lineageTag": "fa918834-02cc-4933-8cba-48359637574e",
                "ordinal": 3
              }
            ],
            "lineageTag": "ba7af033-0eb1-469b-bdd4-fe0ca6c5f652"
          }
        ],
        "isHidden": true,
        "lineageTag": "62bc1cf6-0c00-4c90-93d1-b9e3d7c4859a",
        "partitions": [
          {
            "name": "LocalDateTable_c3c9ee78-a960-40be-96ba-5bcbb968c87e-6be56830-4cda-4648-8c10-584479018e77",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DIMFACTURE'[DATE_FACTURE])), 1, 1), Date(Year(MAX('DIMFACTURE'[DATE_FACTURE])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "DIMPOINTDEVENTE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_PT_VENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "29f78bcc-c30b-4068-a035-18a202f74de4",
            "sourceColumn": "ID_PT_VENTE",
            "summarizeBy": "none"
          },
          {
            "name": "LB_POINT_DE_VENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81c0426b-f084-4e4f-bbd3-fda6a5c59924",
            "sourceColumn": "LB_POINT_DE_VENTE",
            "summarizeBy": "none"
          },
          {
            "name": "LB_PAYS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country",
            "dataType": "string",
            "lineageTag": "2dd463de-858c-415a-bf33-4954e6796850",
            "sourceColumn": "LB_PAYS",
            "summarizeBy": "none"
          },
          {
            "name": "LB_REGION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "County",
            "dataType": "string",
            "lineageTag": "976719f6-e908-45d8-bd46-8333bb50d1e8",
            "sourceColumn": "LB_REGION",
            "summarizeBy": "none"
          },
          {
            "name": "LB_VILLE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "090f080e-bc7e-4c5d-8799-0644d838364b",
            "sourceColumn": "LB_VILLE",
            "summarizeBy": "none"
          },
          {
            "name": "LB_ZONE_GEOGRAPHIQUE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e752f54-4613-4e45-9d88-1eb3f7395a7e",
            "sourceColumn": "LB_ZONE_GEOGRAPHIQUE",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "hierarchie geo",
            "levels": [
              {
                "name": "LB_PAYS",
                "column": "LB_PAYS",
                "lineageTag": "8ae4c534-5c91-4de2-ae0a-b70bd5ad459f",
                "ordinal": 0
              },
              {
                "name": "LB_REGION",
                "column": "LB_REGION",
                "lineageTag": "a3d6e268-4c9c-4e15-873d-de3ed534cdfc",
                "ordinal": 1
              },
              {
                "name": "LB_VILLE",
                "column": "LB_VILLE",
                "lineageTag": "d8451bd7-ce7f-4e23-83ee-9a4103a09556",
                "ordinal": 2
              }
            ],
            "lineageTag": "f09b5238-c7fd-405c-9bcf-ec2cf0bd94db"
          }
        ],
        "lineageTag": "8e9aeebe-d8f7-45f1-923a-1a99e6bdef2c",
        "partitions": [
          {
            "name": "DIMPOINTDEVENTE-18066e72-2fb0-4b70-aacd-0f03d34c70c9",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Odbc.DataSource(Source_BDD, [HierarchicalNavigation=true]),",
                "    M203_Schema = Source{[Name=\"M203\",Kind=\"Schema\"]}[Data],",
                "    DIMPOINTDEVENTE_Table = M203_Schema{[Name=\"DIMPOINTDEVENTE\",Kind=\"Table\"]}[Data]",
                "in",
                "    DIMPOINTDEVENTE_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIMPRODUIT",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_PRODUIT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6ff59bd1-13b9-4d13-a1d3-5a0df4a44bc6",
            "sourceColumn": "ID_PRODUIT",
            "summarizeBy": "none"
          },
          {
            "name": "CD_PRODUIT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c99346be-1f43-4a58-b687-0c6927910b5b",
            "sourceColumn": "CD_PRODUIT",
            "summarizeBy": "none"
          },
          {
            "name": "LB_PRODUIT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a678889c-95cc-4720-9b53-07cff044453e",
            "sourceColumn": "LB_PRODUIT",
            "summarizeBy": "none"
          },
          {
            "name": "LB_SOUS_CATEGORIE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3088229c-f29c-488f-b8e7-77d56b34eed8",
            "sourceColumn": "LB_SOUS_CATEGORIE",
            "summarizeBy": "none"
          },
          {
            "name": "LB_CATEGORIE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dae5e1d8-2aa1-41b2-8c1f-02412501af19",
            "sourceColumn": "LB_CATEGORIE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2a364fe6-e74c-465b-be76-ea3ea3965340",
        "partitions": [
          {
            "name": "DIMPRODUIT-cceb288b-01ad-4bce-8b54-4543cc9ac7b8",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Odbc.DataSource(Source_BDD, [HierarchicalNavigation=true]),",
                "    M203_Schema = Source{[Name=\"M203\",Kind=\"Schema\"]}[Data],",
                "    DIMPRODUIT_Table = M203_Schema{[Name=\"DIMPRODUIT\",Kind=\"Table\"]}[Data]",
                "in",
                "    DIMPRODUIT_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIMRETOURS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_RETOURS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e38a5e7f-0ba6-49fc-a7dd-6fd913479334",
            "sourceColumn": "ID_RETOURS",
            "summarizeBy": "sum"
          },
          {
            "name": "NUM_COMMANDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "deec8f08-803a-485f-87f3-27fe5ff674e3",
            "sourceColumn": "NUM_COMMANDE",
            "summarizeBy": "none"
          },
          {
            "name": "LIB_MOTIF_RETOURS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93175d44-19a0-4dfc-b0a5-8dd6ce5e4413",
            "sourceColumn": "LIB_MOTIF_RETOURS",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6744396b-c9f1-49f2-950e-6ac1741f52e3",
        "partitions": [
          {
            "name": "DIMRETOURS-e87eabcd-1f3e-4dbf-8db7-0df2bf415215",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Odbc.DataSource(Source_BDD, [HierarchicalNavigation=true]),",
                "    M203_Schema = Source{[Name=\"M203\",Kind=\"Schema\"]}[Data],",
                "    DIMRETOURS_Table = M203_Schema{[Name=\"DIMRETOURS\",Kind=\"Table\"]}[Data]",
                "in",
                "    DIMRETOURS_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FAITVENTES",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID_COMMANDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c6c3a4ec-5fe8-4bc0-b294-39c5d13415eb",
            "sourceColumn": "ID_COMMANDE",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CLIENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"FAITVENTES\",\"TableItemName\":\"ID_CLIENT (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"},{\"LinkTarget\":{\"TableName\":\"FAITVENTES\",\"TableItemName\":\"ID_CLIENT (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "double",
            "lineageTag": "cbf1ed6e-aef4-4540-b3eb-1fc91c303c9e",
            "sourceColumn": "ID_CLIENT",
            "summarizeBy": "none"
          },
          {
            "name": "ID_PT_VENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c6eb6597-88b3-40b4-b2bf-d8513ac099c4",
            "sourceColumn": "ID_PT_VENTE",
            "summarizeBy": "none"
          },
          {
            "name": "ID_PRODUIT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "db400247-f5c7-47d7-a553-8813ed4a8643",
            "sourceColumn": "ID_PRODUIT",
            "summarizeBy": "none"
          },
          {
            "name": "ID_RETOURS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "20568919-f285-4b1d-8122-3377462fa9de",
            "sourceColumn": "ID_RETOURS",
            "summarizeBy": "sum"
          },
          {
            "name": "ID_FACTURE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "791f53bb-2631-4c0d-9cbe-7332ea899429",
            "sourceColumn": "ID_FACTURE",
            "summarizeBy": "none"
          },
          {
            "name": "MT_VENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "525cc3e7-4444-45bc-a1a1-e375e442d752",
            "sourceColumn": "MT_VENTE",
            "summarizeBy": "sum"
          },
          {
            "name": "MT_QUANTITE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"FAITVENTES\",\"TableItemName\":\"MT_QUANTITE (compartiments)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9930008a-4000-49a2-8dca-22e08dcd9fc3",
            "sourceColumn": "MT_QUANTITE",
            "summarizeBy": "sum"
          },
          {
            "name": "MT_PROFIT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "024974b3-ed3f-47d5-a4b9-0d82a81b8309",
            "sourceColumn": "MT_PROFIT",
            "summarizeBy": "sum"
          },
          {
            "name": "MT_REMISE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "035329b6-ad52-41d5-bd0e-1e990c8f898e",
            "sourceColumn": "MT_REMISE",
            "summarizeBy": "average"
          },
          {
            "name": "DT_COMMANDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yy",
            "lineageTag": "13df1319-67c4-4d8a-9224-4607c555948f",
            "sourceColumn": "DT_COMMANDE",
            "summarizeBy": "none"
          },
          {
            "name": "DT_EXPEDITION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "e1dae8fb-1b6c-45b6-a684-1594f9e4646c",
            "sourceColumn": "DT_EXPEDITION",
            "summarizeBy": "none"
          },
          {
            "name": "DIMFACTURE.NUM_FACTURE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c209196a-df51-4e3f-b8c1-7a2756d99ca8",
            "sourceColumn": "DIMFACTURE.NUM_FACTURE",
            "summarizeBy": "none"
          },
          {
            "name": "identification commande non facturée",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "75777781-8f18-453f-ba9e-9613f027e4d9",
            "sourceColumn": "identification commande non facturée",
            "summarizeBy": "sum"
          },
          {
            "name": "MT_QUANTITE (compartiments)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"f\",\"Entity\":\"FAITVENTES\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"f\"}},\"Property\":\"MT_QUANTITE\"}}],\"BinItem\":{\"Expression\":{\"Member\":{\"Expression\":{\"Discretize\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"f\"}},\"Property\":\"MT_QUANTITE\"}},\"Count\":7}},\"Member\":\"Min\"}}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "VAR __Count = 7",
              "",
              "VAR __Min = MIN('FAITVENTES'[MT_QUANTITE])",
              "",
              "VAR __Max = MAX('FAITVENTES'[MT_QUANTITE])",
              "",
              "VAR __Difference = (__Max - __Min)",
              "",
              "VAR __Size = IF(__Difference > 0, __Difference / __Count, 1)",
              "",
              "VAR __BinNumber = ",
              "\tIF(",
              "\t\tISBLANK('FAITVENTES'[MT_QUANTITE]),",
              "\t\tBLANK(),",
              "\t\tROUNDDOWN(('FAITVENTES'[MT_QUANTITE] - __Min) / __Size, 0)",
              "\t)",
              "",
              "RETURN",
              "\tIF(",
              "\t\tISBLANK('FAITVENTES'[MT_QUANTITE]),",
              "\t\tBLANK(),",
              "\t\t__Min + (MIN(__BinNumber, __Count - 1) * __Size)",
              "\t)"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "FAITVENTES"
                          }
                        },
                        "Property": "MT_QUANTITE"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "589cfa81-cdeb-4709-88ac-c6022af0e078",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ID_CLIENT (clusters)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"f\",\"Entity\":\"FAITVENTES\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"f\"}},\"Property\":\"ID_CLIENT\"}}],\"PartitionTable\":{\"Definition\":{\"TableDefinition\":{\"Version\":2,\"From\":[{\"Name\":\"t\",\"Entity\":\"Tables Mesures\"},{\"Name\":\"f\",\"Entity\":\"FAITVENTES\"}],\"Where\":[],\"OrderBy\":[],\"Select\":[{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"output0\"}},\"Property\":\"FAITVENTES.ID_CLIENT\"},\"Name\":\"FAITVENTES.ID_CLIENT\"},{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"output0\"}},\"Property\":\"clusterId\"},\"Name\":\"clusterId\"}],\"GroupBy\":[],\"Transform\":[{\"Name\":\"KMeansClustering\",\"Algorithm\":\"KMeansClustering\",\"Input\":{\"Parameters\":[{\"Literal\":{\"Value\":\"-1L\"},\"Name\":\"NumberOfClusters\"}],\"Table\":{\"Name\":\"input0\",\"Columns\":[{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"Total Ventes\"},\"Name\":\"Tables Mesures.Total Ventes\"}},{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"Total Profit\"},\"Name\":\"Tables Mesures.Total Profit\"}},{\"Role\":\"Item\",\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"f\"}},\"Property\":\"ID_CLIENT\"},\"Name\":\"FAITVENTES.ID_CLIENT\"}}]}},\"Output\":{\"Table\":{\"Name\":\"output0\",\"Columns\":[{\"Expression\":{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"input0\"}},\"Property\":\"FAITVENTES.ID_CLIENT\"},\"Name\":\"FAITVENTES.ID_CLIENT\"}},{\"Role\":\"Series\",\"Expression\":{\"TransformOutputRoleRef\":{\"Role\":\"ClusterId\"},\"Name\":\"clusterId\"}}]}}}]},\"ItemIdColumns\":[\"FAITVENTES.ID_CLIENT\"],\"PartitionIdColumn\":\"clusterId\",\"Partitions\":[{\"PartitionIds\":[{\"Literal\":{\"Value\":\"null\"}}]}],\"DefaultPartitionPrefix\":\"Cluster\"},\"Result\":{\"TableName\":\"ClusterMappingTable\",\"PartitionIdColumn\":\"ClusterId\",\"ItemIdMappings\":[[{\"PartitionTableColumn\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Entity\":\"ClusterMappingTable\"}},\"Property\":\"ID_CLIENT\"}},\"SourceTableColumn\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Entity\":\"FAITVENTES\"}},\"Property\":\"ID_CLIENT\"}}}]]}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Clusters pour ID_CLIENT",
            "expression": [
              "VAR __ClusterValue = ",
              "\tLOOKUPVALUE(",
              "\t\t'ClusterMappingTable'[ClusterId],",
              "\t\t'ClusterMappingTable'[ID_CLIENT],",
              "\t\t'FAITVENTES'[ID_CLIENT]",
              "\t)",
              "",
              "RETURN",
              "\tSWITCH(",
              "\t\t__ClusterValue,",
              "\t\tBLANK(),",
              "\t\tBLANK(),",
              "\t\tCONCATENATE(\"Cluster\", __ClusterValue)",
              "\t)"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "FAITVENTES"
                          }
                        },
                        "Property": "ID_CLIENT"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "97f2cd27-336c-4599-bf80-163a1ff733f2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ID_CLIENT (clusters) 2",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"f\",\"Entity\":\"FAITVENTES\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"f\"}},\"Property\":\"ID_CLIENT\"}}],\"PartitionTable\":{\"Definition\":{\"TableDefinition\":{\"Version\":2,\"From\":[{\"Name\":\"t\",\"Entity\":\"Tables Mesures\"},{\"Name\":\"f\",\"Entity\":\"FAITVENTES\"},{\"Name\":\"p\",\"Entity\":\"Paramètre\"}],\"Where\":[{\"Condition\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"Paramètre Champs\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'''Tables Mesures''[Total Ventes]'\"}}]]}}}],\"OrderBy\":[],\"Select\":[{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"output0\"}},\"Property\":\"FAITVENTES.ID_CLIENT\"},\"Name\":\"FAITVENTES.ID_CLIENT\"},{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"output0\"}},\"Property\":\"clusterId\"},\"Name\":\"clusterId\"}],\"GroupBy\":[],\"Transform\":[{\"Name\":\"KMeansClustering\",\"Algorithm\":\"KMeansClustering\",\"Input\":{\"Parameters\":[{\"Literal\":{\"Value\":\"7L\"},\"Name\":\"NumberOfClusters\"}],\"Table\":{\"Name\":\"input0\",\"Columns\":[{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"Total Ventes\"},\"Name\":\"Tables Mesures.Total Ventes\"}},{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"Total Profit\"},\"Name\":\"Tables Mesures.Total Profit\"}},{\"Role\":\"Item\",\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"f\"}},\"Property\":\"ID_CLIENT\"},\"Name\":\"FAITVENTES.ID_CLIENT\"}}]}},\"Output\":{\"Table\":{\"Name\":\"output0\",\"Columns\":[{\"Expression\":{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"input0\"}},\"Property\":\"FAITVENTES.ID_CLIENT\"},\"Name\":\"FAITVENTES.ID_CLIENT\"}},{\"Role\":\"Series\",\"Expression\":{\"TransformOutputRoleRef\":{\"Role\":\"ClusterId\"},\"Name\":\"clusterId\"}}]}}}]},\"ItemIdColumns\":[\"FAITVENTES.ID_CLIENT\"],\"PartitionIdColumn\":\"clusterId\",\"Partitions\":[{\"PartitionIds\":[{\"Literal\":{\"Value\":\"null\"}}]}],\"DefaultPartitionPrefix\":\"Cluster\"},\"Result\":{\"TableName\":\"ClusterMappingTable 2\",\"PartitionIdColumn\":\"ClusterId\",\"ItemIdMappings\":[[{\"PartitionTableColumn\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Entity\":\"ClusterMappingTable 2\"}},\"Property\":\"ID_CLIENT\"}},\"SourceTableColumn\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Entity\":\"FAITVENTES\"}},\"Property\":\"ID_CLIENT\"}}}]]}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Clusters pour ID_CLIENT",
            "expression": [
              "VAR __ClusterValue = ",
              "\tLOOKUPVALUE(",
              "\t\t'ClusterMappingTable 2'[ClusterId],",
              "\t\t'ClusterMappingTable 2'[ID_CLIENT],",
              "\t\t'FAITVENTES'[ID_CLIENT]",
              "\t)",
              "",
              "RETURN",
              "\tSWITCH(",
              "\t\t__ClusterValue,",
              "\t\tBLANK(),",
              "\t\tBLANK(),",
              "\t\tCONCATENATE(\"Cluster\", __ClusterValue)",
              "\t)"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "FAITVENTES"
                          }
                        },
                        "Property": "ID_CLIENT"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "b064f87b-3e66-4eee-a3a3-0df2ce24960a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "6057ea8f-8ab8-49f2-bd72-72d269e03eed",
        "partitions": [
          {
            "name": "FAITVENTES-824edb2b-f9db-4c2f-a76f-46b403966215",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Odbc.DataSource(Source_BDD, [HierarchicalNavigation=true]),",
                "    M203_Schema = Source{[Name=\"M203\",Kind=\"Schema\"]}[Data],",
                "    FAITVENTES_Table = M203_Schema{[Name=\"FAITVENTES\",Kind=\"Table\"]}[Data],",
                "    #\"Requêtes fusionnées\" = Table.NestedJoin(FAITVENTES_Table, {\"ID_FACTURE\"}, DIMFACTURE, {\"ID_FACTURE\"}, \"DIMFACTURE\", JoinKind.LeftOuter),",
                "    #\"DIMFACTURE développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées\", \"DIMFACTURE\", {\"NUM_FACTURE\"}, {\"DIMFACTURE.NUM_FACTURE\"}),",
                "    #\"identification commande non facturée\" = Table.AddColumn(#\"DIMFACTURE développé\", \"Personnalisé\", each if [DIMFACTURE.NUM_FACTURE] = null then 1 else 0),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"identification commande non facturée\",{{\"Personnalisé\", Int64.Type}}),",
                "    #\"Colonnes renommées\" = Table.RenameColumns(#\"Type modifié\",{{\"Personnalisé\", \"identification commande non facturée\"}})",
                "in",
                "    #\"Colonnes renommées\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendrier",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isKey": true,
            "lineageTag": "32c38b75-d68f-417e-83c5-20b1cb434f79",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Année",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "00b7e8b6-b07b-44d7-9eb7-45ed4e31e61f",
            "sourceColumn": "Année",
            "summarizeBy": "none"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "37cfcd6b-277d-4d47-be03-b61132cc6872",
            "sourceColumn": "Trimestre",
            "summarizeBy": "none"
          },
          {
            "name": "MoisNombre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ad9bb9d9-9060-4cfb-bf5e-a4d7ceb20b80",
            "sourceColumn": "MoisNombre",
            "summarizeBy": "none"
          },
          {
            "name": "Jour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b25c793-a09c-4440-a44a-dbc8cfa769c7",
            "sourceColumn": "Jour",
            "summarizeBy": "none"
          },
          {
            "name": "DateNombre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4097247-2f58-4e9e-adef-4ed158d8a8f7",
            "sourceColumn": "DateNombre",
            "summarizeBy": "none"
          },
          {
            "name": "MoisNom",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b34b852-4a6e-475d-b320-9262a0cf8fd2",
            "sortByColumn": "MoisNombre",
            "sourceColumn": "MoisNom",
            "summarizeBy": "none"
          },
          {
            "name": "MoisCalendrier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba8af9e6-a4db-4932-83f8-38dc9f70137f",
            "sourceColumn": "MoisCalendrier",
            "summarizeBy": "none"
          },
          {
            "name": "TrimestreCalendrier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73690ed3-9820-4148-bb0c-68cb60ab3c5c",
            "sourceColumn": "TrimestreCalendrier",
            "summarizeBy": "none"
          },
          {
            "name": "JourSemaine",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89568056-f01e-4b4c-ac10-e12331ade41e",
            "sourceColumn": "JourSemaine",
            "summarizeBy": "none"
          },
          {
            "name": "NomJourSemaine",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "405f689b-60a2-4156-b848-4a47f5eb1735",
            "sourceColumn": "NomJourSemaine",
            "summarizeBy": "none"
          },
          {
            "name": "FinSemaine",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5f37416b-8332-4c1e-839d-203f472d75cb",
            "sourceColumn": "FinSemaine",
            "summarizeBy": "none"
          },
          {
            "name": " Nom jour férie",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2c12d23-abad-4b08-b88a-bb705d2e00a1",
            "sourceColumn": " Nom jour férie",
            "summarizeBy": "none"
          },
          {
            "name": "JourOuvré",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d2f57725-ee72-4aa9-a95d-da08541d0e52",
            "sourceColumn": "JourOuvré",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "2d05096b-09a2-4d76-8ec1-70f2a1901936",
        "partitions": [
          {
            "name": "Calendrier-fcbb2293-c465-4ba2-beae-75e1b0a70503",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = generation_calendrier(#date(2011, 1, 1), #date(2020, 12, 31), null),",
                "    #\"Requêtes fusionnées\" = Table.NestedJoin(Source, {\"Date\"}, #\"Table jours fériés\", {\"Date jour férié\"}, \"Table jours fériés\", JoinKind.LeftOuter),",
                "    #\"Table jours fériés développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées\", \"Table jours fériés\", {\"appel jours fériés.LIBELLE JOUR\"}, {\"appel jours fériés.LIBELLE JOUR\"}),",
                "    #\"Personnalisée ajoutée\" = Table.AddColumn(#\"Table jours fériés développé\", \"JourOuvré\", each if [JourSemaine] < 5 and [appel jours fériés.LIBELLE JOUR] is null then 1 else 0),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"Personnalisée ajoutée\",{{\"JourOuvré\", Int64.Type}}),",
                "    #\"Colonnes renommées\" = Table.RenameColumns(#\"Type modifié\",{{\"appel jours fériés.LIBELLE JOUR\", \" Nom jour férie\"}})",
                "in",
                "    #\"Colonnes renommées\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tables Mesures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5c5dfdec59a246ba9599c0ac0de28e05"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          },
          {
            "name": "__PBI_SemanticLinks",
            "value": "[{\"LinkTarget\":{\"TableName\":\"FAITVENTES\",\"TableItemName\":\"ID_CLIENT (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"},{\"LinkTarget\":{\"TableName\":\"FAITVENTES\",\"TableItemName\":\"ID_CLIENT (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7829c6f4-4f10-417c-867b-85b3e8d493da",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "c97b46b2-e1ae-4adc-b4d8-1ba616b2146f",
        "measures": [
          {
            "name": "Total Ventes",
            "annotations": [
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"FAITVENTES\",\"TableItemName\":\"ID_CLIENT (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"},{\"LinkTarget\":{\"TableName\":\"FAITVENTES\",\"TableItemName\":\"ID_CLIENT (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "expression": "SUM(FAITVENTES[MT_VENTE])",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "be85b99c-287f-4a1a-8246-186df4f06f94"
          },
          {
            "name": "Total Quantité",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(FAITVENTES[MT_QUANTITE] )",
            "lineageTag": "bd41e323-f0cf-4715-84b6-51cd7f576f0e"
          },
          {
            "name": "Total Profit",
            "annotations": [
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"FAITVENTES\",\"TableItemName\":\"ID_CLIENT (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"},{\"LinkTarget\":{\"TableName\":\"FAITVENTES\",\"TableItemName\":\"ID_CLIENT (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "expression": "SUM(FAITVENTES[MT_PROFIT])",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "a05c3161-2b11-4a34-9d8a-3f6e5ec19319"
          },
          {
            "name": "Total Vente (A-1)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Total Ventes],SAMEPERIODLASTYEAR(Calendrier[Date]))",
            "lineageTag": "7e2492cb-3f76-4323-9782-ae4370e02ea7"
          },
          {
            "name": "Total Vente Cumulée Annuel",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Total Ventes],DATESYTD(Calendrier[Date]))",
            "lineageTag": "34da00fd-efb7-4795-8001-3627bfea4b17"
          },
          {
            "name": "Total Profit Cumulé Annuel",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Total Profit],DATESYTD(Calendrier[Date]))",
            "lineageTag": "e59142b5-471d-4d8c-989d-cb8d3fa8e15e"
          },
          {
            "name": "Total Profit Net Cumulé Annuel",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Total Profit Cumulé Annuel] - [Total Remise Cumulé Annuel]",
            "lineageTag": "6d90d06c-06d9-4f74-b36a-860fcf2c72df"
          },
          {
            "name": "Total Remise Cumulé Annuel",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(FAITVENTES[MT_REMISE]),DATESYTD(Calendrier[Date]))",
            "lineageTag": "c063e9d0-3df8-4e36-9a7a-1dd2d9a7256e"
          },
          {
            "name": "Variation Annuelle",
            "expression": "DIVIDE([Total Ventes] - [Total Vente (A-1)],[Total Vente (A-1)])",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "ea545f48-b68a-462c-a296-9a49567331a2"
          },
          {
            "name": "Nombre de commandes",
            "expression": "DISTINCTCOUNT(FAITVENTES[ID_COMMANDE])",
            "formatString": "0",
            "lineageTag": "a2acbeed-a4f4-4b0b-9216-9e7de8d079ea"
          },
          {
            "name": "Nombre de factures",
            "expression": "DISTINCTCOUNT(DIMFACTURE[ID_FACTURE])",
            "formatString": "0",
            "lineageTag": "bc5e56fa-d519-4e60-9652-549355ec2153"
          },
          {
            "name": "Nombre de factures non honorées",
            "expression": "CALCULATE([Nombre de commandes],FAITVENTES[identification commande non facturée]=1)",
            "formatString": "0",
            "lineageTag": "4bcf4667-a5be-4879-89b8-10a106852335"
          },
          {
            "name": "Total Expédié",
            "expression": "sum(DIMCOMMANDE[DATE_EXPEDITION])",
            "formatString": "General Date",
            "lineageTag": "0914f2d9-0641-43d4-8ce8-9b29ad4fbe9c"
          },
          {
            "name": "Delai jours ouvrés",
            "expression": "CALCULATE(SUM(Calendrier[JourOuvré]),Calendrier[Date] > MIN(DIMCOMMANDE[DATE_COMMANDE]),Calendrier[Date] < MAX(DIMCOMMANDE[DATE_EXPEDITION]))",
            "formatString": "0",
            "lineageTag": "538429e6-b4b8-4762-ac02-b47905ce6962"
          },
          {
            "name": "Classement Produit (vente)",
            "expression": "RANKX(ALL(DIMPRODUIT[LB_PRODUIT]),[Total Ventes],,DESC)",
            "formatString": "0",
            "lineageTag": "86d8ebc6-7e66-4515-86c0-c3112f6c67b1"
          },
          {
            "name": "Delai moyen livraison",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Delai jours ouvrés],[Nombre de commandes])",
            "lineageTag": "c4b1bc4a-e010-4f19-b5e5-5e980932b7ef"
          },
          {
            "name": "Classement Produits Francais",
            "expression": "RANKX(ALLSELECTED(DIMPRODUIT[LB_PRODUIT]),CALCULATE([Total Ventes],DIMPOINTDEVENTE[LB_PAYS]=\"France\"),,) ",
            "formatString": "0",
            "lineageTag": "c58cea02-ae05-44d6-9e24-506bada7a006"
          }
        ],
        "partitions": [
          {
            "name": "Tables Mesures",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Paramètre",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "afe5f499edab40e5adaa2eb075918f3e"
          },
          {
            "name": "__PBI_SemanticLinks",
            "value": "[{\"LinkTarget\":{\"TableName\":\"FAITVENTES\",\"TableItemName\":\"ID_CLIENT (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
          }
        ],
        "columns": [
          {
            "name": "Paramètre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "9f07670d-3467-434c-83e8-90d533a93936",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Paramètre Champs"
                }
              ]
            },
            "sortByColumn": "Paramètre Commande",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Paramètre Champs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"FAITVENTES\",\"TableItemName\":\"ID_CLIENT (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "0f725a68-ffec-4fc2-a7c3-5f4cd3e34ce6",
            "sortByColumn": "Paramètre Commande",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Paramètre Commande",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "5598b722-59a6-44dd-92fc-90f2e14d94e6",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "df029507-a7d6-4aa5-b919-c933afcc493a",
        "partitions": [
          {
            "name": "Paramètre",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Total Profit\", NAMEOF('Tables Mesures'[Total Profit]), 0),",
                "    (\"Total Ventes\", NAMEOF('Tables Mesures'[Total Ventes]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "ClusterMappingTable",
        "annotations": [
          {
            "name": "ClusterMappingTable",
            "value": "true"
          },
          {
            "name": "__PBI_SemanticLinks",
            "value": "[{\"LinkTarget\":{\"TableName\":\"FAITVENTES\",\"TableItemName\":\"ID_CLIENT (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
          }
        ],
        "columns": [
          {
            "name": "ID_CLIENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"FAITVENTES\",\"TableItemName\":\"ID_CLIENT (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6466ea51-e4a5-4fd4-b69f-5292aec61da9",
            "sourceColumn": "[ID_CLIENT]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ClusterId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"FAITVENTES\",\"TableItemName\":\"ID_CLIENT (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bb199899-a786-4b29-99bc-901c3a0ada44",
            "sourceColumn": "[ClusterId]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "b6064ddf-b0bd-43c6-a8e8-67b866d6820a",
        "partitions": [
          {
            "name": "ClusterMappingTable",
            "mode": "import",
            "source": {
              "expression": [
                "VAR __DS0Core = ",
                "\tSUMMARIZECOLUMNS(",
                "\t\t'FAITVENTES'[ID_CLIENT],",
                "\t\t\"Total_Ventes\", 'Tables Mesures'[Total Ventes],",
                "\t\t\"Total_Profit\", 'Tables Mesures'[Total Profit]",
                "\t)",
                "",
                "VAR __DataTransformT0 = ",
                "\tKMeansClustering(",
                "\t\tSELECTCOLUMNS(",
                "\t\t\t__DS0Core,",
                "\t\t\t\"ID_CLIENT\", 'FAITVENTES'[ID_CLIENT],",
                "\t\t\t\"Total_Ventes\", [Total_Ventes],",
                "\t\t\t\"Total_Profit\", [Total_Profit]",
                "\t\t),",
                "\t\t{(\"[Total_Ventes]\", \"Attribute\"),",
                "\t\t\t(\"[Total_Profit]\", \"Attribute\"),",
                "\t\t\t(\"[ID_CLIENT]\", \"Item\")},",
                "\t\t{(\"[ID_CLIENT]\", BLANK()),",
                "\t\t\t(\"ClusterId\", \"ClusterId\")},",
                "\t\t-1",
                "\t)",
                "",
                "RETURN __DataTransformT0"
              ],
              "retainDataTillForceCalculate": true,
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "ClusterMappingTable 2",
        "annotations": [
          {
            "name": "ClusterMappingTable",
            "value": "true"
          },
          {
            "name": "__PBI_SemanticLinks",
            "value": "[{\"LinkTarget\":{\"TableName\":\"FAITVENTES\",\"TableItemName\":\"ID_CLIENT (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
          }
        ],
        "columns": [
          {
            "name": "ID_CLIENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"FAITVENTES\",\"TableItemName\":\"ID_CLIENT (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a84acdc2-bd2f-4927-8def-ef9028e6b647",
            "sourceColumn": "[ID_CLIENT]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ClusterId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"FAITVENTES\",\"TableItemName\":\"ID_CLIENT (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3d6161bb-289f-44e4-b4a8-cf4d59c26e6f",
            "sourceColumn": "[ClusterId]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "0e2c46f0-7ec6-43c1-b9ce-39cf733fd823",
        "partitions": [
          {
            "name": "ClusterMappingTable 2",
            "mode": "import",
            "source": {
              "expression": [
                "VAR __DS0FilterTable = ",
                "\tTREATAS({\"'Tables Mesures'[Total Ventes]\"}, 'Paramètre'[Paramètre Champs])",
                "",
                "VAR __DS0Core = ",
                "\tSUMMARIZECOLUMNS(",
                "\t\t'FAITVENTES'[ID_CLIENT],",
                "\t\t__DS0FilterTable,",
                "\t\t\"Total_Ventes\", 'Tables Mesures'[Total Ventes],",
                "\t\t\"Total_Profit\", 'Tables Mesures'[Total Profit]",
                "\t)",
                "",
                "VAR __DataTransformT0 = ",
                "\tKMeansClustering(",
                "\t\tSELECTCOLUMNS(",
                "\t\t\t__DS0Core,",
                "\t\t\t\"ID_CLIENT\", 'FAITVENTES'[ID_CLIENT],",
                "\t\t\t\"Total_Ventes\", [Total_Ventes],",
                "\t\t\t\"Total_Profit\", [Total_Profit]",
                "\t\t),",
                "\t\t{(\"[Total_Ventes]\", \"Attribute\"),",
                "\t\t\t(\"[Total_Profit]\", \"Attribute\"),",
                "\t\t\t(\"[ID_CLIENT]\", \"Item\")},",
                "\t\t{(\"[ID_CLIENT]\", BLANK()),",
                "\t\t\t(\"ClusterId\", \"ClusterId\")},",
                "\t\t7",
                "\t)",
                "",
                "RETURN __DataTransformT0"
              ],
              "retainDataTillForceCalculate": true,
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}